package com.digitalfactory.baseservice.util;

public interface CoreMessageConstants {
    String REQUEST_SUCCESS = "REQUEST_SUCCESS";
    String REQUEST_FAILED = "REQUEST_FAILED";
    String UNEXPECTED_ERROR = "UNEXPECTED_ERROR";
    String MISSING_PARAMETER = "MISSING_PARAMETER";
    String MEDIA_TYPE_NOT_SUPPORTED = "MEDIA_TYPE_NOT_SUPPORTED";
    String METHOD_NOT_FOUND = "METHOD_NOT_FOUND";
    String DATABASE_ERROR = "DATABASE_ERROR";
    String PARAMETER_MISMATCH = "PARAMETER_MISMATCH";
    String MALFORMED_JSON_REQUEST = "MALFORMED_JSON_REQUEST";
    String ERROR_WRITING_JSON = "ERROR_WRITING_JSON";
    String VALIDATION_ERROR = "VALIDATION_ERROR";
    String TRANSACTION_SYSTEM_ERROR = "TRANSACTION_SYSTEM_ERROR";
    String ITEM_ALREADY_EXIST="ITEM_ALREADY_EXIST";

    String ITEM_IS_NOT_FOUND = "ITEM_IS_NOT_FOUND";

    String SLOT_ALREADY_ASSIGNED = "SLOT_ALREADY_ASSIGNED";

    String CROP_ALREADY_ASSIGNED = "CROP_ALREADY_ASSIGNED";





    //"Plot Irrigation slot already assigned at this time."
}
